In [294]:
import pandas as pd
try:
    from StringIO import StringIO
except ImportError:
    from io import StringIO
import numpy as np
import math

In [295]:
#Import 2018 play by play data
mylist = []
for chunk in pd.read_csv(r'nflscrapR-data/play_by_play_data/regular_season/reg_pbp_2018.csv', sep=',', chunksize=20000,low_memory=False):
    mylist.append(chunk)
p18 = pd.concat(mylist, axis = 0)
del mylist

In [296]:
#Import Roster Data
rosters18 = pd.read_csv(r'rosters_2018.csv', sep = ',', low_memory = False)

# Tackle Assists

In [297]:
#Count tackle assists 1-4 
tackleassists18one = pd.DataFrame({'tackles' : p18.groupby( [ "assist_tackle_1_player_id"] ).size()}).reset_index()
tackleassists18two = pd.DataFrame({'tackles' : p18.groupby( [ "assist_tackle_2_player_id"] ).size()}).reset_index()

#Merge all together into one tackle assists dataframe
tackleassists18 = pd.merge(tackleassists18one, tackleassists18two, left_on = 'assist_tackle_1_player_id', right_on = 'assist_tackle_2_player_id', how='left')

In [298]:
#Add the tackles together to get one consolidated tackle assist count for each player
tackleassists18.fillna(0)
tackleassists18['tackle_assists'] = (tackleassists18['tackles_x'] + tackleassists18['tackles_y'])
tackleassists18.drop(columns=['tackles_x', 'assist_tackle_2_player_id','tackles_y'],inplace=True)

In [299]:
#Add the number of tackle assists to the rosters18 dataframe
rosters18 = pd.merge(rosters18, tackleassists18,left_on='GSIS_ID',right_on='assist_tackle_1_player_id', how='left')
#Remove the extra player_id column
rosters18.drop(columns=['assist_tackle_1_player_id'],inplace=True)

In [300]:
#Calculate the tackle assist points for all positions as 0.5 per tackle assist
rosters18['tackle_assist_pts'] = rosters18['tackle_assists']*0.5
rosters18.head()
#Overwrite the tackle assist points for the positions that are calculated differently: CB, DE, DT
#CB tackle assist = 1 point
rosters18.loc[rosters18['Pos']=='CB',['tackle_assist_pts']] = rosters18.loc[rosters18['Pos']=='CB']['tackle_assists']
#DE tackle assist = 1 point
rosters18.loc[rosters18['Pos']=='DE',['tackle_assist_pts']] = rosters18.loc[rosters18['Pos']=='DE']['tackle_assists']
#DT tackle assist = 1.5 points
rosters18.loc[rosters18['Pos']=='DT',['tackle_assist_pts']] = rosters18.loc[rosters18['Pos']=='DT']['tackle_assists'] * 1.5

#Remove the tackle_assists series from the rosters dataframe since we only care about points
rosters18.drop(columns = ['tackle_assists'],inplace=True)
rosters18[rosters18['Pos']=='DT'].head()

,Season,Player,Team,Pos,name,GSIS_ID,tackle_assist_pts
10,2018,Corey Peters,ARI,DT,C.Peters,00-0027686,36.0
34,2018,Olsen Pierre,ARI,DT,O.Pierre,00-0031914,9.0
35,2018,Pasoni Tasini,ARI,DT,P.Tasini,00-0033614,NaN
40,2018,Robert Nkemdiche,ARI,DT,R.Nkemdiche,00-0032761,16.5
41,2018,Rodney Gunter,ARI,DT,R.Gunter,00-0032131,25.5

# QB Hits

In [301]:
qbhit18one = pd.DataFrame({'qb_hit' : p18.groupby( [ "qb_hit_1_player_id"] ).size()}).reset_index()
qbhit18two = pd.DataFrame({'qb_hit' : p18.groupby( [ "qb_hit_2_player_id"] ).size()}).reset_index()

In [302]:
qbhitpts18 = pd.merge(qbhit18one, qbhit18two, left_on = 'qb_hit_1_player_id', right_on = 'qb_hit_2_player_id', how='left')
qbhitpts18.fillna(0, inplace=True)

In [303]:
qbhitpts18['qb_hit_pts'] = qbhitpts18['qb_hit_x'] + qbhitpts18['qb_hit_y']

In [304]:
rosters18 = pd.merge(rosters18, qbhitpts18[['qb_hit_pts','qb_hit_1_player_id']],left_on='GSIS_ID',right_on='qb_hit_1_player_id', how='left')

In [305]:
rosters18.drop(['qb_hit_1_player_id'], axis=1,inplace=True)

# Solo Tackles

In [306]:
#Count tackle assists 1-4 
solotackle18one = pd.DataFrame({'solo_tackles' : p18.groupby( [ "solo_tackle_1_player_id"] ).size()}).reset_index()
solotackle18two = pd.DataFrame({'solo_tackles' : p18.groupby( [ "solo_tackle_2_player_id"] ).size()}).reset_index()

#Merge all together into one tackle assists dataframe
solotackle18 = pd.merge(solotackle18one, solotackle18two, left_on = 'solo_tackle_1_player_id', right_on = 'solo_tackle_2_player_id', how='left')
solotackle18.fillna(0, inplace=True)

In [307]:
#Add the tackles together to get one consolidated tackle assist count for each player
solotackle18.fillna(0, inplace=True)
solotackle18['solo_tackles'] = (solotackle18['solo_tackles_x'] + solotackle18['solo_tackles_y'])
solotackle18.drop(columns=['solo_tackles_x', 'solo_tackle_2_player_id','solo_tackles_y'],inplace=True)

In [308]:
#Add the number of tackle assists to the rosters18 dataframe
rosters18 = pd.merge(rosters18, solotackle18,left_on='GSIS_ID',right_on='solo_tackle_1_player_id', how='left')
#Remove the extra player_id column
rosters18.drop(columns=['solo_tackle_1_player_id'],inplace=True)

In [309]:
#Calculate the tackle points for all positions as 1 per tackle
rosters18['tackle_pts'] = rosters18['solo_tackles']
rosters18.head()
#Overwrite the tackle assist points for the positions that are calculated differently: CB, DE, DT
#CB tackle assist = 1 point
rosters18.loc[rosters18['Pos']=='CB',['tackle_pts']] = rosters18.loc[rosters18['Pos']=='CB']['solo_tackles']
#DE tackle assist = 2 points
rosters18.loc[rosters18['Pos']=='DE',['tackle_pts']] = rosters18.loc[rosters18['Pos']=='DE']['solo_tackles'] * 2
#DT tackle assist = 2.5 points
rosters18.loc[rosters18['Pos']=='DT',['tackle_pts']] = rosters18.loc[rosters18['Pos']=='DT']['solo_tackles'] * 2.5

#Remove the tackle_assists series from the rosters dataframe since we only care about points
rosters18.drop(columns = ['solo_tackles'],inplace=True)
rosters18[rosters18['Pos']=='DT'].head()

,Season,Player,Team,Pos,name,GSIS_ID,tackle_assist_pts,qb_hit_pts,tackle_pts
10,2018,Corey Peters,ARI,DT,C.Peters,00-0027686,36.0,4.0,67.5
34,2018,Olsen Pierre,ARI,DT,O.Pierre,00-0031914,9.0,1.0,15.0
35,2018,Pasoni Tasini,ARI,DT,P.Tasini,00-0033614,NaN,NaN,NaN
40,2018,Robert Nkemdiche,ARI,DT,R.Nkemdiche,00-0032761,16.5,7.0,52.5
41,2018,Rodney Gunter,ARI,DT,R.Gunter,00-0032131,25.5,9.0,67.5

# Fumbles

In [310]:
fumble18 = pd.DataFrame({'fumbles' : p18.groupby( [ "fumbled_1_player_id"] ).size()}).reset_index()
fumble18.fillna(0, inplace=True)

In [311]:
fumble18['fumble_pts'] = fumble18['fumbles'] * -5

In [312]:
rosters18 = pd.merge(rosters18, fumble18[['fumble_pts','fumbled_1_player_id']],left_on='GSIS_ID',right_on='fumbled_1_player_id', how='left')

In [313]:
rosters18.drop(['fumbled_1_player_id'], axis=1,inplace=True)

# Fumble Recovery Yards

In [314]:
recoverydf =p18[["fumble_recovery_1_player_id", "fumble_recovery_1_yards"]]
recoverydf.groupby(["fumble_recovery_1_player_id"]).sum()

                             fumble_recovery_1_yards
fumble_recovery_1_player_id
00-0020531                                       0.0
00-0021140                                       0.0
00-0022161                                      43.0
00-0022787                                       0.0
00-0022803                                       0.0
...                                              ...
00-0034857                                       0.0
00-0034858                                       0.0
00-0034860                                       0.0
00-0034869                                       0.0
00-0034881                                       0.0

[434 rows x 1 columns]

In [315]:
rosters18 = pd.merge(rosters18, recoverydf[["fumble_recovery_1_player_id","fumble_recovery_1_yards"]],left_on='GSIS_ID',right_on="fumble_recovery_1_player_id", how='left')

In [316]:
rosters18['recoveryyard_pts'] = rosters18["fumble_recovery_1_yards"] * 0.15

In [317]:
rosters18.drop(["fumble_recovery_1_player_id","fumble_recovery_1_yards"], axis=1,inplace=True)

# Fumble Recoveries

In [318]:
recovery18 = pd.DataFrame({'recovery' : p18.groupby( [ "fumble_recovery_1_player_id"] ).size()}).reset_index()
recovery18.fillna(0, inplace=True)

In [319]:
recovery18['recovery_pts'] = recovery18['recovery'] * 5

In [320]:
rosters18 = pd.merge(rosters18, recovery18[['recovery_pts','fumble_recovery_1_player_id']],left_on='GSIS_ID',right_on='fumble_recovery_1_player_id', how='left')

In [321]:
rosters18.drop(['fumble_recovery_1_player_id'], axis=1,inplace=True)

# Interceptions Caught

In [322]:
intercept18 = pd.DataFrame({'interceptions' : p18.groupby( [ "interception_player_id"] ).size()}).reset_index()
intercept18.fillna(0, inplace=True)

In [323]:
intercept18['interceptionscaught_pts'] = intercept18['interceptions'] * 6

In [324]:
intercept18 = pd.merge(rosters18, intercept18[['interceptionscaught_pts',"interception_player_id"]],left_on='GSIS_ID',right_on="interception_player_id", how='left')

In [325]:
intercept18.drop(["interception_player_id"], axis=1,inplace=True)

# Passes Defended

In [326]:
passdefend18one = pd.DataFrame({'pass_defend' : p18.groupby( [ "pass_defense_1_player_id"] ).size()}).reset_index()
passdefend18two = pd.DataFrame({'pass_defend' : p18.groupby( [ "pass_defense_2_player_id"] ).size()}).reset_index()

In [327]:
passdefences18 = pd.merge(passdefend18one, passdefend18two, left_on = 'pass_defense_1_player_id', right_on = 'pass_defense_2_player_id', how='left')

In [328]:
passdefences18.fillna(0)
passdefences18['pass_defence_pts'] = (passdefences18['pass_defend_x'] + passdefences18['pass_defend_y']) * 3
passdefences18.drop(columns=['pass_defend_x', 'pass_defense_2_player_id','pass_defend_y'],inplace=True)
passdefences18.head()

  pass_defense_1_player_id  pass_defence_pts
0               00-0021140               NaN
1               00-0022161               NaN
2               00-0022247               NaN
3               00-0023259               NaN
4               00-0023368               NaN

In [329]:
rosters18 = pd.merge(rosters18, passdefences18,left_on='GSIS_ID',right_on='pass_defense_1_player_id', how='left')
rosters18.drop(columns=['pass_defense_1_player_id'],inplace=True)
rosters18.head()

,Season,Player,Team,Pos,name,GSIS_ID,tackle_assist_pts,qb_hit_pts,tackle_pts,fumble_pts,recoveryyard_pts,recovery_pts,pass_defence_pts
0,2018,Antoine Bethea,ARI,FS,A.Bethea,00-0024421,13.5,6.0,93.0,NaN,NaN,NaN,NaN
1,2018,Benson Mayowa,ARI,DE,B.Mayowa,00-0030380,9.0,11.0,58.0,NaN,0.0,5.0,NaN
2,2018,Brandon Williams,ARI,CB,B.Williams,00-0032769,NaN,NaN,10.0,NaN,NaN,NaN,NaN
3,2018,Budda Baker,ARI,SS,B.Baker,00-0033890,15.5,3.0,71.0,NaN,5.4,10.0,NaN
4,2018,Budda Baker,ARI,SS,B.Baker,00-0033890,15.5,3.0,71.0,NaN,-0.3,10.0,NaN

# Forced Fumbles

In [330]:
forcedfumbles18 = pd.DataFrame({'forced_fumbles' : p18.groupby( [ "forced_fumble_player_1_player_id"] ).size()}).reset_index()
forcedfumbles18.fillna(0, inplace=True)

forcedfumbles18['forced_fumble_pts'] = forcedfumbles18['forced_fumbles'] * 6

rosters18 = pd.merge(rosters18, forcedfumbles18[['forced_fumble_pts','forced_fumble_player_1_player_id']],left_on='GSIS_ID',right_on='forced_fumble_player_1_player_id', how='left')

rosters18.drop(['forced_fumble_player_1_player_id'], axis=1,inplace=True)

# Blocked Punts

In [331]:
blockedpunt18 = pd.DataFrame({'blocked_punt' : p18.groupby( [ "blocked_player_id"] ).size()}).reset_index()
blockedpunt18.fillna(0, inplace=True)

blockedpunt18['blocked_punt_pts'] = blockedpunt18['blocked_punt'] * 7

rosters18 = pd.merge(rosters18, blockedpunt18[['blocked_punt_pts','blocked_player_id']],left_on='GSIS_ID',right_on='blocked_player_id', how='left')

rosters18.drop(['blocked_player_id'], axis=1,inplace=True)

rosters18.head()

,Season,Player,Team,Pos,name,GSIS_ID,tackle_assist_pts,qb_hit_pts,tackle_pts,fumble_pts,recoveryyard_pts,recovery_pts,pass_defence_pts,forced_fumble_pts,blocked_punt_pts
0,2018,Antoine Bethea,ARI,FS,A.Bethea,00-0024421,13.5,6.0,93.0,NaN,NaN,NaN,NaN,6.0,NaN
1,2018,Benson Mayowa,ARI,DE,B.Mayowa,00-0030380,9.0,11.0,58.0,NaN,0.0,5.0,NaN,6.0,NaN
2,2018,Brandon Williams,ARI,CB,B.Williams,00-0032769,NaN,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN
3,2018,Budda Baker,ARI,SS,B.Baker,00-0033890,15.5,3.0,71.0,NaN,5.4,10.0,NaN,6.0,NaN
4,2018,Budda Baker,ARI,SS,B.Baker,00-0033890,15.5,3.0,71.0,NaN,-0.3,10.0,NaN,6.0,NaN

# Interception Return Yards

In [332]:
#Make df of non-lateral interceptions
intreturn18 = p18[['interception',"interception_player_id", "return_yards"]]
intreturn18 = intreturn18[intreturn18['interception']==1]
intreturn18.drop(columns='interception',inplace=True)
#Group by sum of player's int return yards
intreturn18.groupby(["interception_player_id"]).sum()
#Calculate Points
intreturn18['int_return_yard_pts'] = intreturn18['return_yards'] * 0.15
intreturn18
rosters18 = pd.merge(rosters18, intreturn18[['int_return_yard_pts',"interception_player_id"]],left_on='GSIS_ID',right_on='interception_player_id', how='left')
rosters18.drop(columns='interception_player_id',axis=1,inplace=True)
rosters18

,Season,Player,Team,Pos,name,GSIS_ID,tackle_assist_pts,qb_hit_pts,tackle_pts,fumble_pts,recoveryyard_pts,recovery_pts,pass_defence_pts,forced_fumble_pts,blocked_punt_pts,int_return_yard_pts
0,2018,Antoine Bethea,ARI,FS,A.Bethea,00-0024421,13.5,6.0,93.0,NaN,NaN,NaN,NaN,6.0,NaN,NaN
1,2018,Benson Mayowa,ARI,DE,B.Mayowa,00-0030380,9.0,11.0,58.0,NaN,0.00,5.0,NaN,6.0,NaN,NaN
2,2018,Brandon Williams,ARI,CB,B.Williams,00-0032769,NaN,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2018,Budda Baker,ARI,SS,B.Baker,00-0033890,15.5,3.0,71.0,NaN,5.40,10.0,NaN,6.0,NaN,NaN
4,2018,Budda Baker,ARI,SS,B.Baker,00-0033890,15.5,3.0,71.0,NaN,-0.30,10.0,NaN,6.0,NaN,NaN
5,2018,Cameron Malveaux,ARI,DE,C.Malveaux,00-0033403,8.0,1.0,4.0,NaN,NaN,NaN,NaN,NaN,7.0,NaN
6,2018,Chad Williams,ARI,WR,C.Williams,00-0033933,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2018,Chandler Jones,ARI,DE,C.Jones,00-0029585,13.0,18.0,72.0,NaN,0.00,5.0,NaN,18.0,NaN,NaN
8,2018,Chase Edmonds,ARI,RB,C.Edmonds,00-0034681,NaN,NaN,9.0,-5.0,NaN,NaN,NaN,NaN,NaN,NaN
9,2018,Chris Jones,ARI,DB,C.Jones,00-0034641,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2018,Christian Kirk,ARI,WR,C.Kirk,00-0034775,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,2018,Corey Peters,ARI,DT,C.Peters,00-0027686,36.0,4.0,67.5,NaN,0.00,5.0,NaN,NaN,NaN,NaN
12,2018,D.J. Swearinger,ARI,FS,D.Swearinger,00-0030566,7.5,1.0,38.0,NaN,0.00,5.0,30.0,18.0,NaN,0.60
13,2018,D.J. Swearinger,ARI,FS,D.Swearinger,00-0030566,7.5,1.0,38.0,NaN,0.00,5.0,30.0,18.0,NaN,1.05
14,2018,D.J. Swearinger,ARI,FS,D.Swearinger,00-0030566,7.5,1.0,38.0,NaN,0.00,5.0,30.0,18.0,NaN,0.00
15,2018,D.J. Swearinger,ARI,FS,D.Swearinger,00-0030566,7.5,1.0,38.0,NaN,0.00,5.0,30.0,18.0,NaN,3.30
16,2018,Darrell Daniels,ARI,TE,D.Daniels,00-0033258,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,2018,David Amerson,ARI,DB,D.Amerson,00-0030420,2.5,NaN,16.0,NaN,NaN,NaN,NaN,NaN,NaN,3.75
18,2018,David Johnson,ARI,RB,D.Johnson,00-0032187,NaN,NaN,2.0,-15.0,0.00,5.0,NaN,NaN,NaN,NaN
19,2018,Deatrick Nichols,ARI,CB,D.Nichols,00-0034481,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,2018,Dennis Gardeck,ARI,LB,D.Gardeck,00-0034473,NaN,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,2018,Deone Bucannon,ARI,OLB,D.Bucannon,00-0031366,5.0,2.0,28.0,NaN,0.60,5.0,NaN,6.0,NaN,NaN
22,2018,Derrick Coleman,ARI,FB,D.Coleman,00-0029068,NaN,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,2018,Dontae Johnson,ARI,DB,D.Johnson,00-0031061,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,2018,Gerald Hodges,ARI,LB,G.Hodges,00-0030385,7.5,1.0,40.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,2018,Haason Reddick,ARI,OLB,H.Reddick,00-0033875,15.5,6.0,49.0,NaN,NaN,NaN,NaN,6.0,NaN,NaN
26,2018,J.J. Nelson,ARI,WR,J.Nelson,00-0032112,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,2018,Jalen Tolliver,ARI,WR,J.Tolliver,00-0034489,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,2018,Jermaine Gresham,ARI,TE,J.Gresham,00-0027873,NaN,NaN,NaN,-5.0,NaN,NaN,NaN,NaN,NaN,NaN
29,2018,Joe Walker,ARI,LB,J.Walker,00-0032809,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1873,2018,Joshua Holsey,WAS,CB,J.Holsey,00-0033533,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1874,2018,Marcus Smith,WAS,LB,M.Smith,00-0031371,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1875,2018,Mark Sanchez,WAS,QB,M.Sanchez,00-0026898,NaN,NaN,1.0,-5.0,0.00,5.0,NaN,NaN,NaN,NaN
1876,2018,Marquis Flowers,WAS,LB,M.Flowers,00-0031290,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1877,2018,Mason Foster,WAS,ILB,M.Foster,00-0028022,33.0,1.0,67.0,NaN,0.00,10.0,12.0,NaN,NaN,0.60
1878,2018,Mason Foster,WAS,ILB,M.Foster,00-0028022,33.0,1.0,67.0,NaN,0.00,10.0,12.0,NaN,NaN,0.00
1879,2018,Mason Foster,WAS,ILB,M.Foster,00-0028022,33.0,1.0,67.0,NaN,0.00,10.0,12.0,NaN,NaN,0.60
1880,2018,Mason Foster,WAS,ILB,M.Foster,00-0028022,33.0,1.0,67.0,NaN,0.00,10.0,12.0,NaN,NaN,0.00
1881,2018,Matt Flanagan,WAS,TE,M.Flanagan,00-0034101,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1882,2018,Matthew Ioannidis,WAS,DE,M.Ioannidis,00-0032781,12.0,11.0,38.0,NaN,0.00,5.0,NaN,6.0,NaN,NaN
1883,2018,Maurice Harris,WAS,WR,M.Harris,00-0032362,NaN,NaN,1.0,-5.0,0.00,5.0,NaN,NaN,NaN,NaN
1884,2018,Michael Floyd,WAS,WR,M.Floyd,00-0029638,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1885,2018,Montae Nicholson,WAS,SS,M.Nicholson,00-0033527,8.0,NaN,25.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1886,2018,Paul Richardson,WAS,WR,P.Richardson,00-0031257,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1887,2018,Pernell McPhee,WAS,LB,P.McPhee,00-0028103,1.5,8.0,8.0,NaN,3.60,5.0,NaN,NaN,NaN,NaN
1888,2018,Preston Smith,WAS,OLB,P.Smith,00-0031935,13.5,16.0,25.0,NaN,0.15,5.0,NaN,NaN,NaN,0.45
1889,2018,Quinton Dunbar,WAS,CB,Q.Dunbar,00-0032007,10.0,NaN,29.0,NaN,NaN,NaN,27.0,NaN,NaN,-0.45
1890,2018,Quinton Dunbar,WAS,CB,Q.Dunbar,00-0032007,10.0,NaN,29.0,NaN,NaN,NaN,27.0,NaN,NaN,3.60
1891,2018,Rob Kelley,WAS,RB,R.Kelley,00-0032371,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1892,2018,Ryan Anderson,WAS,LB,R.Anderson,00-0033525,5.5,4.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1893,2018,Ryan Kerrigan,WAS,OLB,R.Kerrigan,00-0027954,7.0,19.0,29.0,NaN,0.00,5.0,NaN,18.0,NaN,NaN
1894,2018,Samaje Perine,WAS,RB,S.Perine,00-0033526,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1895,2018,Shaun Dion Hamilton,WAS,LB,S.Hamilton,00-0034336,6.0,5.0,16.0,NaN,NaN,NaN,NaN,6.0,NaN,NaN
1896,2018,Stacy McGee,WAS,DT,S.McGee,00-0030515,4.5,1.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1897,2018,Tim Settle,WAS,DT,T.Settle,00-0034397,NaN,NaN,12.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1898,2018,Trey Quinn,WAS,WR,T.Quinn,00-0034339,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1899,2018,Troy Apke,WAS,DB,T.Apke,00-0034334,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1900,2018,Vernon Davis,WAS,TE,V.Davis,00-0024221,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1901,2018,Zach Brown,WAS,ILB,Z.Brown,00-0029566,18.0,2.0,60.0,NaN,NaN,NaN,NaN,12.0,NaN,NaN
1902,2018,Zach Vigil,WAS,LB,Z.Vigil,00-0031728,2.0,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Write to Excel (This must be final cell)

In [333]:
rosters18.fillna(0, inplace=True)
rosters18.to_excel('output.xlsx', engine='xlsxwriter')